---
- name: snmp ro/rw string configuration
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
  become: yes
  become_method: enable  
  collections:
    - cisco.ios

  tasks:

    - name: gather facts
      ios_config:
        # available_network_resources: true
        #gather_network_resources: all
        commands:
          username adduser1 password addpassword
        when: ios_facts['ansible_net_hostname']== "VIOS1"  
              #- snmp-server community ansible-public RO
              #- snmp-server community ansible-private RW
        commands:
          username adduser password addpassword
        when: ios_facts['ansible_net_hostname']== ""VIOS" 
